-- Actualizar tabla liquidaciones para que coincida con el código
-- La tabla ya existe con esta estructura:
-- CREATE TABLE public.liquidaciones (
--   id bigint generated by default as identity not null,
--   creado_el timestamp with time zone not null default now(),
--   fk_empleado bigint null,
--   desde timestamp without time zone null,
--   hasta timestamp without time zone null,
--   sueldo_base numeric null,
--   total_adelantos numeric null,
--   total_faltas numeric null,
--   neto_liquidado numeric null,
--   constraint liquidaciones_pkey primary key (id),
--   constraint liquidaciones_fk_empleado_fkey foreign KEY (fk_empleado) references empleados (id)
-- )

-- Agregar columnas faltantes que necesita el código
ALTER TABLE public.liquidaciones 
ADD COLUMN IF NOT EXISTS total_ventas numeric(10,2) DEFAULT 0;

ALTER TABLE public.liquidaciones 
ADD COLUMN IF NOT EXISTS comision numeric(10,2) DEFAULT 0;

ALTER TABLE public.liquidaciones 
ADD COLUMN IF NOT EXISTS total_liquidacion numeric(10,2) DEFAULT 0;

ALTER TABLE public.liquidaciones 
ADD COLUMN IF NOT EXISTS estado text DEFAULT 'pendiente';

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_liquidaciones_fk_empleado ON public.liquidaciones (fk_empleado);
CREATE INDEX IF NOT EXISTS idx_liquidaciones_desde ON public.liquidaciones (desde);
CREATE INDEX IF NOT EXISTS idx_liquidaciones_hasta ON public.liquidaciones (hasta);

-- Comentarios para documentar
COMMENT ON COLUMN public.liquidaciones.fk_empleado IS 'Referencia al empleado liquidado';
COMMENT ON COLUMN public.liquidaciones.desde IS 'Fecha de inicio del período de liquidación';
COMMENT ON COLUMN public.liquidaciones.hasta IS 'Fecha de fin del período de liquidación';
COMMENT ON COLUMN public.liquidaciones.sueldo_base IS 'Sueldo base del empleado';
COMMENT ON COLUMN public.liquidaciones.total_adelantos IS 'Total de adelantos realizados';
COMMENT ON COLUMN public.liquidaciones.total_faltas IS 'Total de faltas descontadas';
COMMENT ON COLUMN public.liquidaciones.neto_liquidado IS 'Monto neto a pagar al empleado';
COMMENT ON COLUMN public.liquidaciones.total_ventas IS 'Total de ventas del período';
COMMENT ON COLUMN public.liquidaciones.comision IS 'Comisión calculada';
COMMENT ON COLUMN public.liquidaciones.total_liquidacion IS 'Total de la liquidación';
COMMENT ON COLUMN public.liquidaciones.estado IS 'Estado de la liquidación (pendiente, pagado, etc.)';
